#include "localization.h"

#include <cwchar>

namespace {

const LanguageOption kLanguageOptions[] = {
    {LangAuto},
    {LangChinese},
    {LangChineseTraditional},
    {LangEnglish},
    {LangKorean},
    {LangJapanese},
    {LangRussian},
    {LangGerman}
};

const wchar_t* const kTextEn[TxtTextCount] = {
    L"Starting",
    L"HDR SDR Brightness",
    L"Apply now",
    L"Settings...",
    L"Start with Windows",
    L"Open Display settings",
    L"Open Night Light settings",
    L"Exit",
    L"HDR SDR Brightness Assistant Settings",
    L"Adjust SDR content brightness automatically while HDR is enabled.",
    L"Language",
    L"Auto",
    L"English",
    L"Chinese",
    L"Korean",
    L"Japanese",
    L"Russian",
    L"Traditional Chinese",
    L"German",
    L"SDR content brightness",
    L"Day",
    L"Night",
    L"Appearance",
    L"Behavior",
    L"Follow Windows Night Light",
    L"Auto restore manual brightness changes",
    L"Start with Windows",
    L"Fallback schedule",
    L"Switching",
    L"Follow system",
    L"Default schedule",
    L"Windows Night Light is not enabled or cannot be read. Use the default schedule instead.",
    L"SDR content brightness follows Windows Night Light.",
    L"Night starts",
    L"Day starts",
    L"OK",
    L"Apply",
    L"Cancel",
    L"Day SDR content brightness must be 0-100.",
    L"Night SDR content brightness must be 0-100.",
    L"Schedule time is invalid.",
    L"Windows Night Light",
    L"Fixed",
    L"Settings preview",
    L"{0} {1}-{2}",
    L"Applied with DWM fallback",
    L"Applied to {0}/{1} HDR",
    L"No active HDR display found",
    L"No HDR",
    L"No HDR display",
    L"Apply failed, error {0}",
    L"via",
    L"SDR content brightness restored",
    L"Auto restore is enabled, so SDR content brightness is being restored to {0}.",
    L"SDR content brightness notification",
    L"Manual SDR content brightness changed; auto restore is off",
    L"To stop the app from interfering with manual adjustments, open Settings and turn off \"{0}\".",
    L"Unsaved changes",
    L"SDR content brightness {0} {1}",
    L"Restoring SDR content brightness {0}",
    L"SDR content brightness {0} {1}",
    L"HDR {0}/{1}",
    L"Restore",
    L"on",
    L"off",
    L"{0}%",
    L"--%",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"SDR content brightness: {0} for {1}. {2}.",
    L"SDR content",
    L"HDR content",
    L"Current state",
    L"Restore on",
    L"Restore off",
    L"Support author...",
    L"Support author",
    L"Buy the author a coffee. After donating, enter your supporter code to unlock a badge.",
    L"Supporter code",
    L"Donate",
    L"Activate",
    L"Supporter",
    L"Thanks for the coffee!",
    L"Thank you for supporting this app.",
    L"Invalid supporter code.",
    L"Coffee time",
    L"If this app helps your HDR setup, consider buying the author a coffee.",
    L"Windows HDR Calibration",
    L"Calibrate HDR display",
    L"Calibrate",
    L"HDR washed out or clipped? Calibrate your display first.",
    L"HDR SDR Brightness adjusts SDR content brightness. Microsoft's HDR Calibration app helps tune HDR peak brightness and tone mapping."
};

const wchar_t* const kTextZh[TxtTextCount] = {
    L"启动中",
    L"HDR SDR 亮度助手",
    L"立即应用",
    L"设置...",
    L"开机自启",
    L"打开显示设置",
    L"打开夜间模式设置",
    L"退出",
    L"HDR SDR Brightness Assistant 设置",
    L"在开启 HDR 时自动调整 SDR 内容亮度。",
    L"语言",
    L"自动",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"SDR 内容亮度",
    L"白天",
    L"夜间",
    L"外观",
    L"行为",
    L"跟随 Windows 夜间模式",
    L"自动纠正手动调整",
    L"开机自启",
    L"默认时段",
    L"切换方式",
    L"跟随系统",
    L"默认时段",
    L"未检测到可跟随的 Windows 夜间模式，请使用默认时段。",
    L"SDR 内容亮度将跟随 Windows 夜间模式自动切换。",
    L"夜间模式开始",
    L"白天模式开始",
    L"确定",
    L"应用",
    L"取消",
    L"白天 SDR 内容亮度必须为 0-100。",
    L"夜间 SDR 内容亮度必须为 0-100。",
    L"时段设置无效。",
    L"Windows 夜间模式",
    L"固定时段",
    L"设置预览",
    L"{0} {1}-{2}",
    L"已使用 DWM 兜底方式应用",
    L"已应用到 {0}/{1} 台 HDR 屏幕",
    L"未找到已启用 HDR 的显示器",
    L"无 HDR",
    L"无 HDR 屏幕",
    L"应用失败，错误 {0}",
    L"跟随",
    L"正在恢复 SDR 内容亮度",
    L"已开启自动纠正手动调整，正在将 SDR 内容亮度恢复到 {0}。",
    L"SDR 内容亮度通知",
    L"检测到手动修改 SDR 内容亮度；自动恢复已关闭",
    L"如果不想让软件干涉手动调整，请在设置中关闭“{0}”。",
    L"有未保存更改",
    L"SDR 内容亮度 {0} {1}",
    L"SDR 内容亮度恢复中 {0}",
    L"SDR 内容亮度 {0} {1}",
    L"HDR 屏幕 {0}/{1}",
    L"自动纠正",
    L"开",
    L"关",
    L"{0}％",
    L"--％",
    L"已同步 {0} 台 HDR 屏幕",
    L"已同步 {0} 台，共 {1} 台 HDR 屏幕",
    L"已同步 {0} 台",
    L"SDR 内容亮度：{1} {0}，{2}。",
    L"SDR 内容",
    L"HDR 内容",
    L"当前状态",
    L"纠正开启",
    L"纠正关闭",
    L"支持作者...",
    L"支持作者",
    L"请作者喝杯咖啡。捐赠后输入支持者码，即可解锁徽标。",
    L"支持者码",
    L"去捐赠",
    L"激活",
    L"支持者",
    L"感谢你的咖啡！",
    L"感谢你支持这个软件。",
    L"支持者码无效。",
    L"请作者喝杯咖啡",
    L"如果这个工具改善了你的 HDR 使用体验，可以考虑请作者喝杯咖啡。",
    L"Windows HDR 校准",
    L"校准 HDR 显示器",
    L"去校准",
    L"HDR 发灰或过曝？建议先校准显示器。",
    L"HDR SDR 亮度助手负责调整 SDR 内容亮度。Microsoft 的 HDR 校准应用可帮助校准 HDR 峰值亮度和色调映射。"
};

const wchar_t* const kTextKo[TxtTextCount] = {
    L"시작 중",
    L"HDR SDR 밝기 도우미",
    L"지금 적용",
    L"설정...",
    L"Windows 시작 시 실행",
    L"디스플레이 설정 열기",
    L"야간 모드 설정 열기",
    L"종료",
    L"HDR SDR Brightness Assistant 설정",
    L"HDR이 켜져 있을 때 SDR 콘텐츠 밝기를 자동으로 조정합니다.",
    L"언어",
    L"자동",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"SDR 콘텐츠 밝기",
    L"낮",
    L"밤",
    L"모양",
    L"동작",
    L"Windows 야간 모드 따르기",
    L"수동 밝기 변경 자동 복원",
    L"Windows 시작 시 실행",
    L"대체 일정",
    L"전환 방식",
    L"시스템 따르기",
    L"기본 일정",
    L"Windows 야간 모드가 켜져 있지 않거나 읽을 수 없습니다. 대신 기본 일정을 사용하세요.",
    L"SDR 콘텐츠 밝기가 Windows 야간 모드를 따라 자동으로 전환됩니다.",
    L"야간 시작",
    L"주간 시작",
    L"확인",
    L"적용",
    L"취소",
    L"낮 SDR 콘텐츠 밝기는 0-100이어야 합니다.",
    L"밤 SDR 콘텐츠 밝기는 0-100이어야 합니다.",
    L"일정 시간이 올바르지 않습니다.",
    L"Windows 야간 모드",
    L"고정",
    L"설정 미리 보기",
    L"{0} {1}-{2}",
    L"DWM 대체 방식으로 적용됨",
    L"{0}/{1} HDR에 적용됨",
    L"활성 HDR 디스플레이를 찾을 수 없습니다",
    L"HDR 없음",
    L"HDR 디스플레이 없음",
    L"적용 실패, 오류 {0}",
    L"경유",
    L"SDR 콘텐츠 밝기가 복원됨",
    L"자동 복원이 켜져 있어 SDR 콘텐츠 밝기를 {0}(으)로 복원합니다.",
    L"SDR 콘텐츠 밝기 알림",
    L"수동 SDR 콘텐츠 밝기 변경이 감지되었습니다. 자동 복원이 꺼져 있습니다",
    L"수동 조정에 앱이 개입하지 않게 하려면 설정에서 \"{0}\"을 끄세요.",
    L"저장되지 않은 변경 사항",
    L"SDR 콘텐츠 밝기 {0} {1}",
    L"SDR 콘텐츠 밝기 복원 중 {0}",
    L"SDR 콘텐츠 밝기 {0} {1}",
    L"HDR {0}/{1}",
    L"복원",
    L"켜짐",
    L"꺼짐",
    L"{0}%",
    L"--%",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"SDR 콘텐츠 밝기: {1} {0}. {2}.",
    L"SDR 콘텐츠",
    L"HDR 콘텐츠",
    L"현재 상태",
    L"복원 켜짐",
    L"복원 꺼짐",
    L"개발자 후원...",
    L"개발자 후원",
    L"커피 한 잔으로 개발자를 후원하세요. 후원 후 후원자 코드를 입력하면 배지가 표시됩니다.",
    L"후원자 코드",
    L"후원하기",
    L"활성화",
    L"후원자",
    L"커피 후원 고마워요!",
    L"이 앱을 후원해 주셔서 감사합니다.",
    L"후원자 코드가 올바르지 않습니다.",
    L"커피 타임",
    L"이 앱이 HDR 환경에 도움이 된다면 개발자에게 커피 한 잔을 후원해 주세요.",
    L"Windows HDR 보정",
    L"HDR 디스플레이 보정",
    L"보정하기",
    L"HDR이 흐리거나 과하면 먼저 디스플레이를 보정하세요.",
    L"HDR SDR Brightness는 SDR 콘텐츠 밝기를 조정합니다. Microsoft HDR 보정 앱은 HDR 최대 밝기와 톤 매핑을 조정하는 데 도움이 됩니다."
};

const wchar_t* const kTextJa[TxtTextCount] = {
    L"起動中",
    L"HDR SDR 輝度アシスタント",
    L"今すぐ適用",
    L"設定...",
    L"Windows 起動時に実行",
    L"ディスプレイ設定を開く",
    L"夜間モード設定を開く",
    L"終了",
    L"HDR SDR Brightness Assistant 設定",
    L"HDR が有効なときに SDR コンテンツの輝度を自動調整します。",
    L"言語",
    L"自動",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"SDR コンテンツ輝度",
    L"昼",
    L"夜",
    L"外観",
    L"動作",
    L"Windows 夜間モードに従う",
    L"手動の輝度変更を自動復元",
    L"Windows 起動時に実行",
    L"代替スケジュール",
    L"切り替え方式",
    L"システムに従う",
    L"既定の時間帯",
    L"Windows 夜間モードが有効でないか読み取れません。代わりに既定の時間帯を使用してください。",
    L"SDR コンテンツ輝度は Windows 夜間モードに従って自動的に切り替わります。",
    L"夜の開始",
    L"昼の開始",
    L"OK",
    L"適用",
    L"キャンセル",
    L"昼の SDR コンテンツ輝度は 0-100 で指定してください。",
    L"夜の SDR コンテンツ輝度は 0-100 で指定してください。",
    L"スケジュール時刻が正しくありません。",
    L"Windows 夜間モード",
    L"固定",
    L"設定プレビュー",
    L"{0} {1}-{2}",
    L"DWM フォールバックで適用済み",
    L"{0}/{1} HDR に適用済み",
    L"有効な HDR ディスプレイが見つかりません",
    L"HDR なし",
    L"HDR ディスプレイなし",
    L"適用に失敗しました。エラー {0}",
    L"経由",
    L"SDR コンテンツ輝度を復元しました",
    L"自動復元が有効なため、SDR コンテンツ輝度を {0} に復元しています。",
    L"SDR コンテンツ輝度の通知",
    L"SDR コンテンツ輝度が手動で変更されました。自動復元はオフです",
    L"手動調整にアプリが干渉しないようにするには、設定で「{0}」をオフにしてください。",
    L"未保存の変更",
    L"SDR コンテンツ輝度 {0} {1}",
    L"SDR コンテンツ輝度を復元中 {0}",
    L"SDR コンテンツ輝度 {0} {1}",
    L"HDR {0}/{1}",
    L"復元",
    L"オン",
    L"オフ",
    L"{0}%",
    L"--%",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"SDR コンテンツ輝度: {1} {0}。{2}。",
    L"SDR コンテンツ",
    L"HDR コンテンツ",
    L"現在の状態",
    L"復元オン",
    L"復元オフ",
    L"作者を支援...",
    L"作者を支援",
    L"作者にコーヒーを一杯。寄付後に支援者コードを入力するとバッジが表示されます。",
    L"支援者コード",
    L"寄付",
    L"有効化",
    L"支援者",
    L"コーヒーをありがとう！",
    L"このアプリを支援していただきありがとうございます。",
    L"支援者コードが無効です。",
    L"コーヒーの時間",
    L"このアプリが HDR 環境に役立っているなら、作者にコーヒーを一杯贈ってください。",
    L"Windows HDR Calibration",
    L"HDR ディスプレイを調整",
    L"調整する",
    L"HDR が白っぽい/明るすぎる場合は先に調整してください。",
    L"HDR SDR Brightness は SDR コンテンツの明るさを調整します。Microsoft の HDR Calibration アプリは HDR のピーク輝度とトーンマッピング調整に役立ちます。"
};

const wchar_t* const kTextRu[TxtTextCount] = {
    L"Запуск",
    L"HDR SDR Brightness",
    L"Применить сейчас",
    L"Настройки...",
    L"Запускать с Windows",
    L"Открыть настройки дисплея",
    L"Открыть настройки ночного света",
    L"Выход",
    L"Настройки HDR SDR Brightness Assistant",
    L"Автоматически настраивает яркость SDR-контента при включенном HDR.",
    L"Язык",
    L"Авто",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"Яркость SDR-контента",
    L"День",
    L"Ночь",
    L"Внешний вид",
    L"Поведение",
    L"Следовать ночному свету Windows",
    L"Автовосстановление ручных изменений",
    L"Запускать с Windows",
    L"Резервное расписание",
    L"Переключение",
    L"Система",
    L"По умолч.",
    L"Ночной свет Windows не включен или недоступен для чтения. Используйте расписание по умолчанию.",
    L"Яркость SDR-контента автоматически следует ночному свету Windows.",
    L"Ночь начинается",
    L"День начинается",
    L"ОК",
    L"Применить",
    L"Отмена",
    L"Дневная яркость SDR-контента должна быть от 0 до 100.",
    L"Ночная яркость SDR-контента должна быть от 0 до 100.",
    L"Недопустимое время расписания.",
    L"Ночной свет Windows",
    L"Фиксированное",
    L"Предпросмотр настроек",
    L"{0} {1}-{2}",
    L"Применено через резервный DWM",
    L"Применено к {0}/{1} HDR",
    L"Активный HDR-дисплей не найден",
    L"Нет HDR",
    L"Нет HDR-дисплея",
    L"Не удалось применить, ошибка {0}",
    L"через",
    L"Яркость SDR-контента восстановлена",
    L"Автовосстановление включено, яркость SDR-контента восстанавливается до {0}.",
    L"Уведомление о яркости SDR-контента",
    L"Яркость SDR-контента изменена вручную; автовосстановление выключено",
    L"Чтобы приложение не вмешивалось в ручные изменения, откройте настройки и выключите \"{0}\".",
    L"Не сохранено",
    L"Яркость SDR-контента {0} {1}",
    L"Восстановление яркости SDR-контента {0}",
    L"Яркость SDR-контента {0} {1}",
    L"HDR {0}/{1}",
    L"Восст.",
    L"вкл.",
    L"выкл.",
    L"{0}%",
    L"--%",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"Яркость SDR-контента: {1} {0}. {2}.",
    L"SDR-контент",
    L"HDR-контент",
    L"Текущее состояние",
    L"Восст. вкл.",
    L"Восст. выкл.",
    L"Поддержать автора...",
    L"Поддержать автора",
    L"Купите автору кофе. После доната введите код, чтобы открыть значок.",
    L"Код поддержки",
    L"Донат",
    L"Акт.",
    L"Поддержал",
    L"Спасибо за кофе!",
    L"Спасибо за поддержку приложения.",
    L"Недействительный код поддержки.",
    L"Время для кофе",
    L"Если приложение помогает с HDR, угостите автора кофе.",
    L"Windows HDR Calibration",
    L"Калибровать HDR-дисплей",
    L"Калибровать",
    L"HDR блеклый или пересвечен? Сначала откалибруйте дисплей.",
    L"HDR SDR Brightness настраивает яркость SDR-контента. Приложение Microsoft HDR Calibration помогает настроить пиковую яркость HDR и тональное отображение."
};

const wchar_t* const kTextZhTw[TxtTextCount] = {
    L"啟動中",
    L"HDR SDR 亮度助手",
    L"立即套用",
    L"設定...",
    L"開機自啟",
    L"開啟顯示設定",
    L"開啟夜間模式設定",
    L"結束",
    L"HDR SDR Brightness Assistant 設定",
    L"在開啟 HDR 時自動調整 SDR 內容亮度。",
    L"語言",
    L"自動",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"SDR 內容亮度",
    L"白天",
    L"夜間",
    L"外觀",
    L"行為",
    L"跟隨 Windows 夜間模式",
    L"自動修正手動調整",
    L"開機自啟",
    L"預設時段",
    L"切換方式",
    L"跟隨系統",
    L"預設時段",
    L"未偵測到可跟隨的 Windows 夜間模式，請使用預設時段。",
    L"SDR 內容亮度將跟隨 Windows 夜間模式自動切換。",
    L"夜間模式開始",
    L"白天模式開始",
    L"確定",
    L"套用",
    L"取消",
    L"白天 SDR 內容亮度必須為 0-100。",
    L"夜間 SDR 內容亮度必須為 0-100。",
    L"時段設定無效。",
    L"Windows 夜間模式",
    L"固定時段",
    L"設定預覽",
    L"{0} {1}-{2}",
    L"已使用 DWM 後援方式套用",
    L"已套用到 {0}/{1} 台 HDR 螢幕",
    L"未找到已啟用 HDR 的顯示器",
    L"無 HDR",
    L"無 HDR 螢幕",
    L"套用失敗，錯誤 {0}",
    L"透過",
    L"SDR 內容亮度已還原",
    L"已開啟自動修正手動調整，正在將 SDR 內容亮度還原到 {0}。",
    L"SDR 內容亮度通知",
    L"偵測到手動修改 SDR 內容亮度；自動還原已關閉",
    L"如果不想讓軟體干涉手動調整，請在設定中關閉「{0}」。",
    L"有未儲存的變更",
    L"SDR 內容亮度 {0} {1}",
    L"SDR 內容亮度還原中 {0}",
    L"SDR 內容亮度 {0} {1}",
    L"HDR 螢幕 {0}/{1}",
    L"自動修正",
    L"開",
    L"關",
    L"{0}%",
    L"--%",
    L"已同步 {0} 台 HDR 螢幕",
    L"已同步 {0} 台，共 {1} 台 HDR 螢幕",
    L"已同步 {0} 台",
    L"SDR 內容亮度：{1} {0}，{2}。",
    L"SDR 內容",
    L"HDR 內容",
    L"目前狀態",
    L"修正開啟",
    L"修正關閉",
    L"支持作者...",
    L"支持作者",
    L"請作者喝杯咖啡。捐贈後輸入支持者碼，即可解鎖徽標。",
    L"支持者碼",
    L"去捐贈",
    L"啟用",
    L"支持者",
    L"感謝你的咖啡！",
    L"感謝你支持這個軟體。",
    L"支持者碼無效。",
    L"請作者喝杯咖啡",
    L"如果這個工具改善了你的 HDR 使用體驗，可以考慮請作者喝杯咖啡。",
    L"Windows HDR 校正",
    L"校正 HDR 顯示器",
    L"去校正",
    L"HDR 發灰或過曝？建議先校正顯示器。",
    L"HDR SDR 亮度助手負責調整 SDR 內容亮度。Microsoft 的 HDR 校正應用程式可協助校正 HDR 峰值亮度和色調映射。"
};

const wchar_t* const kTextDe[TxtTextCount] = {
    L"Wird gestartet",
    L"HDR SDR Brightness",
    L"Jetzt anwenden",
    L"Einstellungen...",
    L"Mit Windows starten",
    L"Anzeigeeinstellungen öffnen",
    L"Nachtlichteinstellungen öffnen",
    L"Beenden",
    L"HDR SDR Brightness Assistant Einstellungen",
    L"Passt die Helligkeit von SDR-Inhalten automatisch an, wenn HDR aktiviert ist.",
    L"Sprache",
    L"Automatisch",
    L"English",
    L"中文",
    L"한국어",
    L"日本語",
    L"Русский",
    L"繁體中文",
    L"Deutsch",
    L"SDR-Inhaltshelligkeit",
    L"Tag",
    L"Nacht",
    L"Darstellung",
    L"Verhalten",
    L"Windows-Nachtlicht folgen",
    L"Manuelle Helligkeitsänderungen automatisch wiederherstellen",
    L"Mit Windows starten",
    L"Ersatzzeitplan",
    L"Umschaltung",
    L"System folgen",
    L"Standardzeitplan",
    L"Windows-Nachtlicht ist nicht aktiviert oder kann nicht gelesen werden. Verwende stattdessen den Standardzeitplan.",
    L"Die SDR-Inhaltshelligkeit folgt automatisch dem Windows-Nachtlicht.",
    L"Nacht beginnt",
    L"Tag beginnt",
    L"OK",
    L"Anwenden",
    L"Abbrechen",
    L"Die SDR-Inhaltshelligkeit am Tag muss 0-100 betragen.",
    L"Die SDR-Inhaltshelligkeit in der Nacht muss 0-100 betragen.",
    L"Die Zeitplaneinstellung ist ungültig.",
    L"Windows-Nachtlicht",
    L"Fest",
    L"Einstellungsvorschau",
    L"{0} {1}-{2}",
    L"Mit DWM-Fallback angewendet",
    L"Auf {0}/{1} HDR angewendet",
    L"Kein aktives HDR-Display gefunden",
    L"Kein HDR",
    L"Kein HDR-Display",
    L"Anwenden fehlgeschlagen, Fehler {0}",
    L"über",
    L"SDR-Inhaltshelligkeit wiederhergestellt",
    L"Automatische Wiederherstellung ist aktiviert, daher wird die SDR-Inhaltshelligkeit auf {0} zurückgesetzt.",
    L"Benachrichtigung zur SDR-Inhaltshelligkeit",
    L"SDR-Inhaltshelligkeit wurde manuell geändert; automatische Wiederherstellung ist aus",
    L"Damit die App manuelle Anpassungen nicht beeinflusst, öffne Einstellungen und deaktiviere \"{0}\".",
    L"Nicht gespeicherte Änderungen",
    L"SDR-Inhaltshelligkeit {0} {1}",
    L"SDR-Inhaltshelligkeit wird wiederhergestellt {0}",
    L"SDR-Inhaltshelligkeit {0} {1}",
    L"HDR {0}/{1}",
    L"Wiederher.",
    L"ein",
    L"aus",
    L"{0}%",
    L"--%",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"HDR {0}/{1}",
    L"SDR-Inhaltshelligkeit: {1} {0}. {2}.",
    L"SDR-Inhalt",
    L"HDR-Inhalt",
    L"Aktueller Status",
    L"Wiederher. ein",
    L"Wiederher. aus",
    L"Autor unterstützen...",
    L"Autor unterstützen",
    L"Gib dem Autor einen Kaffee aus. Nach der Spende den Unterstützer-Code eingeben.",
    L"Unterstützer-Code",
    L"Spenden",
    L"Aktivieren",
    L"Unterstützer",
    L"Danke für den Kaffee!",
    L"Danke für deine Unterstützung.",
    L"Ungültiger Unterstützer-Code.",
    L"Kaffeezeit",
    L"Wenn diese App deinem HDR-Setup hilft, spendiere dem Autor gern einen Kaffee.",
    L"Windows HDR Calibration",
    L"HDR-Anzeige kalibrieren",
    L"Kalibrieren",
    L"HDR wirkt blass oder überbelichtet? Kalibriere zuerst den Bildschirm.",
    L"HDR SDR Brightness passt die Helligkeit von SDR-Inhalten an. Microsofts HDR Calibration-App hilft bei HDR-Spitzenhelligkeit und Tonemapping."
};

const wchar_t* const* TextTableForLanguage(int language) {
    switch (NormalizeLanguageChoice(language)) {
    case LangChinese:
        return kTextZh;
    case LangChineseTraditional:
        return kTextZhTw;
    case LangKorean:
        return kTextKo;
    case LangJapanese:
        return kTextJa;
    case LangRussian:
        return kTextRu;
    case LangGerman:
        return kTextDe;
    case LangEnglish:
    case LangAuto:
    default:
        return kTextEn;
    }
}

void ReplaceAll(std::wstring* text, const std::wstring& needle, const std::wstring& replacement) {
    if (!text || needle.empty()) return;

    size_t pos = 0;
    while ((pos = text->find(needle, pos)) != std::wstring::npos) {
        text->replace(pos, needle.size(), replacement);
        pos += replacement.size();
    }
}

}  // namespace

int NormalizeLanguageChoice(int language) {
    for (int i = 0; i < LanguageOptionCount(); ++i) {
        if (kLanguageOptions[i].id == language) return language;
    }
    return LangAuto;
}

const LanguageOption* LanguageOptions() {
    return kLanguageOptions;
}

int LanguageOptionCount() {
    return static_cast<int>(sizeof(kLanguageOptions) / sizeof(kLanguageOptions[0]));
}

const wchar_t* LocalizedText(int language, TextId id) {
    if (id < 0 || id >= TxtTextCount) return L"";
    return TextTableForLanguage(language)[id];
}

const wchar_t* LocalizedLanguageName(int uiLanguage, int language) {
    switch (NormalizeLanguageChoice(language)) {
    case LangEnglish:
        return LocalizedText(uiLanguage, TxtLanguageEnglish);
    case LangChinese:
        return LocalizedText(uiLanguage, TxtLanguageChinese);
    case LangKorean:
        return LocalizedText(uiLanguage, TxtLanguageKorean);
    case LangJapanese:
        return LocalizedText(uiLanguage, TxtLanguageJapanese);
    case LangRussian:
        return LocalizedText(uiLanguage, TxtLanguageRussian);
    case LangChineseTraditional:
        return LocalizedText(uiLanguage, TxtLanguageChineseTraditional);
    case LangGerman:
        return LocalizedText(uiLanguage, TxtLanguageGerman);
    case LangAuto:
    default:
        return LocalizedText(uiLanguage, TxtLanguageAuto);
    }
}

bool IsLocalizedTextValue(TextId id, const std::wstring& value) {
    return value == LocalizedText(LangEnglish, id) ||
           value == LocalizedText(LangChinese, id) ||
           value == LocalizedText(LangKorean, id) ||
           value == LocalizedText(LangJapanese, id) ||
           value == LocalizedText(LangRussian, id) ||
           value == LocalizedText(LangChineseTraditional, id) ||
           value == LocalizedText(LangGerman, id);
}

std::wstring FormatLocalizedText(int language, TextId id, const std::vector<std::wstring>& args) {
    std::wstring text = LocalizedText(language, id);
    for (size_t i = 0; i < args.size(); ++i) {
        wchar_t token[8] = {};
        swprintf(token, L"{%u}", static_cast<unsigned>(i));
        ReplaceAll(&text, token, args[i]);
    }
    return text;
}

std::wstring FormatLocalizedText(int language, TextId id, std::initializer_list<std::wstring> args) {
    return FormatLocalizedText(language, id, std::vector<std::wstring>(args));
}
